// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace NPC.Server.EntityModels;

public partial class NPCTableContext : DbContext
{
    public NPCTableContext(DbContextOptions<NPCTableContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TblTest> TblTests { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TblTest>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("tbl_Test");

            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}