// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NPC.Server.EntityModels;

public partial class TblUser
{
    public int Id { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string NameThai { get; set; }

    public string NameEnglish { get; set; }

    public string Gender { get; set; }

    public long? Phone { get; set; }

    public string Email { get; set; }

    public string CompanyId { get; set; }

    public string CompanyName { get; set; }

    public int? PositionId { get; set; }

    public int? RoleId { get; set; }

    public string ImagePath { get; set; }

    public string VerificationCode { get; set; }

    public bool? IsVerified { get; set; }

    public string FacebookToken { get; set; }

    public string LineToken { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public virtual TblRole Role { get; set; }
}